name: List Files on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: self-hosted

    steps:
      - name: Request approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: "dchoi1"
          minimum-approvals: 1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set PATH 
        run: echo "/mybin" >> "$GITHUB_PATH"

      - name: Check PATH variable
        run: echo $PATH

      - name: Check GITHUB_PATH variable
        run: echo "$GITHUB_PATH"

      - name: execute WOW
        run: wow.sh
