name: List Files

on: 
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the runner
        run: ls -l
