name: path check now

on: 
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: self-hosted

#    env:
#      PATH: "$PATH:/mybin"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: path2
        run: echo $PATH
