name: List Files on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: self-hosted

    env:
      PATH: "/home/runner/custom-path:$PATH"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PATH variable
        run: echo $PATH

