name: List Files

on: 
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: path1
        run: echo $PATH
